version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/myapp'
    command: /bin/sh -c "yarn dev"
    tty: true
    stdin_open: true
    env_file:
      - .env

  api:
    build:
      context: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - './api:/myapp'
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - '3010:3000'
    tty: true
    stdin_open: true
    env_file:
      - .env

  db:
    image: postgres:12.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
